name: trackbound
description: A Flutter app for railway enthusiasts to log and visualise train journeys.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.0.0
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  flutter_map_tile_caching: ^8.0.1
  sqflite: ^2.0.0+4
  path_provider: ^2.0.0
  dio: ^5.0.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  sqflite_common_ffi: ^2.2.0

flutter:
  uses-material-design: true
